<a href="https://colab.research.google.com/github/Just-polite/DAV_Colab/blob/main/4IK25CS187_EXP_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python for Data Analytics -Numpy , Pandas, Reading csv/json, indexing, filtering, grouping and aggregation

1.Basic Numpy Operations

In [ ]:
import numpy as np
import pandas as pd
marks=np.array([88,72,95,60,79])
print("Array: ",marks)
print("Mean: ",marks.mean())
print("Max: ",marks.max())
print("Min: ",marks.min())

Array:  [88 72 95 60 79]
Mean:  78.8
Max:  95
Min:  60

2. Create a Sample CSV File

In [ ]:
data={
    "name":["Asha","Ravi","Meena","Kiran","Deepa"],
    "department":["CSE","ECE","CSE","ME","ECE"],
    "marks":[88,72,95,60,79]
}
df=pd.DataFrame(data)
df.to_csv("Students.csv",index=False)
df.to_json("Students.json",orient="records")

3. Reading CSV and JSON files

In [ ]:
print("\n----Reading CSV----")
df_csv=pd.read_csv("Students.csv")
print(df_csv)

----Reading CSV----
    name department  marks
0   Asha        CSE     88
1   Ravi        ECE     72
2  Meena        CSE     95
3  Kiran         ME     60
4  Deepa        ECE     79

In [ ]:
print("\n----Reading JSON----")
df_json=pd.read_json("Students.json")
print(df_json)

----Reading JSON----
    name department  marks
0   Asha        CSE     88
1   Ravi        ECE     72
2  Meena        CSE     95
3  Kiran         ME     60
4  Deepa        ECE     79

4. Indexing

In [ ]:
print("First marks: ",marks[0])
print("Second marks: ",marks[1])
print("Last marks: ",marks[-1])

First marks:  88
Second marks:  72
Last marks:  79

In [ ]:
print("Marks column:")
print(df["marks"])
print("\nBranch and Marks column:")
print(df[["department","marks"]])

Marks column:
0    88
1    72
2    95
3    60
4    79
Name: marks, dtype: int64

Branch and Marks column:
  department  marks
0        CSE     88
1        ECE     72
2        CSE     95
3         ME     60
4        ECE     79

In [ ]:
print("Index 1 to 3: ",marks[1:4])
print("First three: ",marks[:3])
print("From index 2: ",marks[2:])
print("Every second element: ",marks[::2])

Index 1 to 3:  [72 95 60]
First three:  [88 72 95]
From index 2:  [95 60 79]
Every second element:  [88 95 79]

5. Filtering

In [ ]:
high_scorers = df[df["marks"]>90]
high_scorers

    name department  marks
2  Meena        CSE     95

In [ ]:
print("Students from CSE:")
display(df[df["department"] == "CSE"])

print("\nStudents scoring 85 or above:")
display(df[df["marks"] >= 85])

Students from CSE:

    name department  marks
0   Asha        CSE     88
2  Meena        CSE     95

Students scoring 85 or above:

    name department  marks
0   Asha        CSE     88
2  Meena        CSE     95

6. Grouping And Aggregation

In [ ]:
print("Average marks per department:")
print(df.groupby("department")["marks"].mean())

Average marks per department:
department
CSE    91.5
ECE    75.5
ME     60.0
Name: marks, dtype: float64

In [ ]:
print("\nNumber of students per department:")
print(df.groupby("department")["name"].count())

Number of students per department:
department
CSE    2
ECE    2
ME     1
Name: name, dtype: int64